#!/bin/bash
# .git/hooks/commit-msg

COMMIT_MSG_FILE="$1"
COMMIT_MESSAGE=$(cat "$COMMIT_MSG_FILE")
REGEX='^(feat|fix|docs|style|refactor|test|chore)\(.*\):\ .+'

if [[ ! "$COMMIT_MESSAGE" =~ $REGEX ]]; then
    echo "Invalid commit message format. Use conventional commit format (e.g., 'feat: added new feature')."
    exit 1
fi
1
exit 0