#!/bin/bash
# .git/hooks/pre-commit

echo "Running pre-commit checks..."

# Run pre-commit formatting and linting
make pre-commit
if [ $? -ne 0 ]; then
    echo "Pre-commit checks failed."
    exit 1
fi

echo "Pre-commit checks passed."
exit 0