name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run code formatting
        run: |
          poetry run black .

      - name: Run linting
        run: |
          poetry run flake8 .

      - name: Run static type checking
        run: |
          poetry run mypy .

      - name: Run docstring check
        run: |
          poetry run pydocstyle .

      - name: Run tests
        run: |
          poetry run pytest

      - name: Check outdated dependencies
        run: |
          poetry show --outdated

      - name: Validate PR title
        if: github.event_name == 'pull_request'
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
          if [[ ! "$PR_TITLE" =~ ^\[PR-[0-9]+\]:\ .+ ]]; then
            echo "Invalid PR title format. It should be '[PR-x]: ...'"
            exit 1
          fi

          PREVIOUS_PR_NUMBER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed" \
            | jq -r '.[] | select(.title | startswith("[PR-")) | .number' \
            | sort -n | tail -n1)

          if [ "$PREVIOUS_PR_NUMBER" != "" ] && [ "$PR_NUMBER" -ne "$((PREVIOUS_PR_NUMBER + 1))" ]; then
            echo "PR number must be consecutive. Expected: $((PREVIOUS_PR_NUMBER + 1))"
            exit 1
          fi