name: Docstrings Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docstring-check:
    name: Check for docstrings
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Install pydocstyle
      run: |
        poetry add --dev pydocstyle

    - name: Run pydocstyle
      run: |
        poetry run pydocstyle .
      continue-on-error: true

    - name: Report docstring issues
      if: failure()
      run: |
        echo "Docstring checks failed. Please ensure that all functions, classes, and modules have appropriate docstrings."
        echo "Please run 'make check-docstring' to check which docstrings are not appropriate."
        echo "You can check the detailed pydocstyle output for specifics."
